
[versions]
datafaker= "2.5.3"
flyway="12.0.0"
hikaricp = "7.0.2"
jackson-datatype-jsr = "2.20.1"
koin="4.1.1"
kotest-extensions="2.0.0"
kotest="6.1.2"
kotlin-version = "2.3.0"
ktor-version = "3.4.0"
logback-version = "1.5.27"
micrometer-prometheus = "1.16.2"
mockk="1.14.9"
postgresql = "42.7.9"
testcontainers = "1.21.4"
fasterxml-uuid = "5.2.0"
logstashEncoder = "9.0"

[libraries]
database-flyway-core = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
database-hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
database-postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
datafaker = {module = "net.datafaker:datafaker", version.ref = "datafaker"}
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version = "jackson-datatype-jsr" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-logger = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
kotest-assertions-core = {module = "io.kotest:kotest-assertions-core", version.ref = "kotest"}
kotest-assertions-ktor = {module = "io.kotest.extensions:kotest-assertions-ktor", version.ref = "kotest-extensions"}
kotest-junit = {module = "io.kotest:kotest-runner-junit5", version.ref = "kotest"}
kotest-property = {module = "io.kotest:kotest-property", version.ref = "kotest"}
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor-version" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor-version" }
ktor-server-micrometer = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-version" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor-version" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor-version" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer-prometheus" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers"}
testcontainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainers"}
logstash = {module = "net.logstash.logback:logstash-logback-encoder",  version.ref = "logstashEncoder"}
fasterxml-uuid = { module = "com.fasterxml.uuid:java-uuid-generator", version.ref = "fasterxml-uuid" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }

[bundles]
kotest = ["kotest-assertions-core", "kotest-junit", "kotest-property", "kotest-assertions-ktor"]
database = ["database-flyway-core", "database-hikaricp", "database-postgresql"]
testcontainers = ["testcontainers", "testcontainers-postgres"]
